application: tw-stock
version: 1
runtime: python
api_version: 1

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

## CSS
- url: /css
  static_dir: static/css
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

## cron
#- url: /crondata
#  script: crondata.py
  #secure: always
#  login: admin

## Main WSGI
- url: .*
  script: main.py
  #secure: always
  #login: admin
